# Test against this version of Node.js
environment:
  nodejs_version: "4.2"

# Install scripts. (runs after repo cloning)
install:
  - ps: Install-Product node $env:nodejs_version
  - npm install -g purescript pulp bower
  - bower install
  - npm install

# Post-install test scripts.
test_script:
  - node --version
  - npm --version
  - psc --version
  - npm run build
  - npm run test
